/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package socket;

/**
 *
 * @author kingdragon
 */
public class calculete extends javax.swing.JFrame {

    /**
     * Creates new form calculete
     */
    public calculete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textfield = new javax.swing.JTextField();
        jButtonV = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtondiv = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonProd = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButtonEq = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldActionPerformed(evt);
            }
        });
        getContentPane().add(textfield);
        textfield.setBounds(120, 30, 220, 29);

        jButtonV.setText(".");
        getContentPane().add(jButtonV);
        jButtonV.setBounds(90, 230, 17, 31);

        jButton7.setText("7");
        getContentPane().add(jButton7);
        jButton7.setBounds(20, 100, 21, 31);

        jButton8.setText("8");
        getContentPane().add(jButton8);
        jButton8.setBounds(90, 100, 21, 31);

        jButton5.setText("5");
        getContentPane().add(jButton5);
        jButton5.setBounds(90, 150, 21, 31);

        jButton6.setText("6");
        getContentPane().add(jButton6);
        jButton6.setBounds(160, 150, 21, 31);

        jButton1.setText("1");
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 190, 21, 31);

        jButtondiv.setText("/");
        getContentPane().add(jButtondiv);
        jButtondiv.setBounds(240, 100, 18, 31);

        jButton2.setText("2");
        getContentPane().add(jButton2);
        jButton2.setBounds(90, 190, 21, 31);

        jButtonProd.setText("x");
        getContentPane().add(jButtonProd);
        jButtonProd.setBounds(240, 150, 20, 31);

        jButton9.setText("9");
        getContentPane().add(jButton9);
        jButton9.setBounds(160, 100, 21, 31);

        jButtonMinus.setText("-");
        getContentPane().add(jButtonMinus);
        jButtonMinus.setBounds(240, 190, 18, 31);

        jButton0.setText("0");
        getContentPane().add(jButton0);
        jButton0.setBounds(20, 230, 21, 31);

        jButton4.setText("4");
        getContentPane().add(jButton4);
        jButton4.setBounds(20, 150, 21, 31);

        jButtonEq.setText("=");
        getContentPane().add(jButtonEq);
        jButtonEq.setBounds(160, 230, 21, 31);

        jButtonPlus.setText("+");
        getContentPane().add(jButtonPlus);
        jButtonPlus.setBounds(240, 230, 21, 31);

        jButton3.setText("3");
        getContentPane().add(jButton3);
        jButton3.setBounds(160, 190, 21, 31);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonEq;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JButton jButtonProd;
    private javax.swing.JButton jButtonV;
    private javax.swing.JButton jButtondiv;
    private javax.swing.JTextField textfield;
    // End of variables declaration//GEN-END:variables
}
