
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zakaria
 */
public class aff extends javax.swing.JFrame {

    /**
     * Creates new form aff
     */
    Connection con;
    DefaultTableModel dts ;
    public aff() {
        initComponents();
         init(false);
       setVisible(true);
       this.setSize(900, 500);
       jLabel13.setVisible(false);
       jTextField13.setVisible(false);
       con=BaseDonne.getInstance().getConnexion();
       dts=(DefaultTableModel) jTable1.getModel();
        Afficher();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelxx = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextFieldxx = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Code Frs", "Fournisseur", "Saisie/Arret", "Commande/Marche", "Ville", "Agence", "Banque", "N°Compte", "Date Ecrit", "Date MAJ", "N_Order", "Arrivee"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 10, 860, 160);

        jPanel1.setBackground(new java.awt.Color(0, 255, 51));
        jPanel1.setLayout(null);

        jButton1.setText("modifier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 230, 80, 31);

        jButton2.setText("quitter");
        jPanel1.add(jButton2);
        jButton2.setBounds(0, 360, 80, 31);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 80, 590);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(290, 190, 240, 29);

        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 190, 140, 30);

        jLabel2.setText("Code Frs");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 220, 130, 30);

        jLabel3.setText("Fourni");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 250, 140, 30);

        jLabel4.setText("Saiasie");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 280, 140, 30);

        jLabel5.setText("Comm");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 310, 140, 30);

        jLabel6.setText("Ville");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 340, 150, 30);

        jLabel7.setText("Agence");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 370, 150, 30);

        jLabel8.setText("Banque");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(120, 400, 150, 30);

        jLabel9.setText("N Com");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(120, 430, 150, 30);

        jLabel10.setText("Date Ecrit");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(120, 460, 150, 30);

        jLabel11.setText("Date Maj");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(120, 490, 140, 30);

        jLabelxx.setText("Arrivee");
        getContentPane().add(jLabelxx);
        jLabelxx.setBounds(120, 550, 150, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(290, 220, 240, 29);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(290, 250, 240, 29);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(290, 280, 240, 29);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(290, 310, 240, 29);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(290, 340, 240, 29);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(290, 370, 240, 29);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(290, 400, 240, 29);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(290, 430, 240, 29);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(290, 460, 240, 29);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(290, 490, 240, 29);
        getContentPane().add(jTextFieldxx);
        jTextFieldxx.setBounds(290, 550, 240, 29);

        jLabel13.setText("ID");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(600, 260, 110, 40);

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField13);
        jTextField13.setBounds(730, 260, 180, 29);

        jButton3.setText("Chercher");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(730, 310, 160, 31);

        jLabel14.setText("N Order");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(120, 520, 150, 30);
        getContentPane().add(jTextField14);
        jTextField14.setBounds(290, 520, 240, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private boolean mod()
    {
         PreparedStatement state;
              
         try {
             state=con.prepareStatement("SELECT attestation_rib.ID,attestation_rib.Code_Frs,fournisseur.Fournisseur,attestation_rib.Saisie_Arret,attestation_rib.Commande_Marche,ville.Ville,ville.Agence,banque.Banque,banque.N_Compte,attestation_rib.Date_Ecrit,attestation_rib.Dte_MAJ,attestation_rib.N_Ordre,attestation_rib.Arrivee FROM attestation_rib,fournisseur,ville,banque WHERE ID=? && attestation_rib.Code_Frs=fournisseur.Code_Frs && attestation_rib.Banque=ville.id && banque.id_Ville=ville.id");
             state.setInt(1, Integer.valueOf(jTextField13.getText()));
             ResultSet result=state.executeQuery();
             if(result.next())
             { 
        

        jTextField1.setText(""+result.getInt(1));
        jTextField2.setText(""+result.getInt(2));
        jTextField3.setText(result.getString(3));
        jTextField4.setText(result.getString(4));
        jTextField5.setText(result.getString(5));
        jTextField6.setText(result.getString(6));
        jTextField7.setText(result.getString(7));
        jTextField8.setText(result.getString(8));
        jTextField9.setText(""+result.getInt(9));
        jTextField10.setText(result.getString(10));
        jTextField11.setText(result.getString(11));
        jTextField14.setText(result.getString(12));
        jTextFieldxx.setText(result.getString(13));
        
        return true;
             }else
             {
                 JOptionPane.showMessageDialog(this,"non trouve!!!");
                 return false;
             }

         } catch (SQLException ex) {
           
         }
        return false;
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!jTextField13.isVisible())
        {
            init(true);
            return;
        }
       
        PreparedStatement state;
        try {
            state=con.prepareStatement("UPDATE `attestation_rib` SET `ID`=?,`Code_Frs`=?,`Saisie_Arret`=?,`Commande_Marche`=?,`Date_Ecrit`=?,`Dte_MAJ`=?,`N_Ordre`=?,`Arrivee`=? WHERE ID=?");
            state.setInt(1, Integer.valueOf(jTextField1.getText()));
            state.setInt(2, Integer.valueOf(jTextField2.getText()));
            state.setString(3, jTextField3.getText());
            state.setString(4,jTextField5.getText());
    
            state.setString(5,jTextField10.getText());
            state.setString(6,jTextField11.getText());
            state.setString(7,jTextField14.getText());
            state.setString(8,jTextField14.getText());
  
            state.setInt(9,Integer.valueOf(jTextField13.getText()));

            state.executeUpdate();
           //state=con.prepareStatement("UPDATE `banque` SET `Banque`=?,`N_Compte`=? WHERE id_Ville=?");
           //state.setString(1, jTextField8.getText());
          // state.setInt(1, Integer.valueOf(jTextField9.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(aff.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        mod();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aff().setVisible(true);
            }
        });
    }

    private void init(boolean flag)
    {
         jTextField1.setVisible(flag);jTextField2.setVisible(flag);jTextField3.setVisible(flag);jTextField4.setVisible(flag);
        jTextField5.setVisible(flag);jTextField6.setVisible(flag);jTextField7.setVisible(flag);jTextField8.setVisible(flag);
        jTextField9.setVisible(flag);jTextField10.setVisible(flag);jTextField11.setVisible(flag);
        jTextField14.setVisible(flag);jTextFieldxx.setVisible(flag);
        jLabel1.setVisible(flag);jLabel2.setVisible(flag);jLabel3.setVisible(flag);jLabel4.setVisible(flag);jLabel5.setVisible(flag);
        jLabel6.setVisible(flag);jLabel7.setVisible(flag);jLabel8.setVisible(flag);jLabel9.setVisible(flag);jLabel10.setVisible(flag);jLabel11.setVisible(flag);
        jLabel14.setVisible(flag);jLabelxx.setVisible(flag);
        jTextField13.setVisible(flag);jLabel13.setVisible(flag);
        jButton3.setVisible(flag);
    }
        
    public void Afficher(){
        PreparedStatement state;
               
        ResultSet rs;
        
    try{
          state=con.prepareStatement("select * from attestation_rib");
           rs=state.executeQuery();
dts.setRowCount(0);
      while(rs.next()){
            
            int id=rs.getInt(1);
            int codef=rs.getInt(2);
            String dates=rs.getString(3);
            String cmd=rs.getString(4);
            int banque=rs.getInt(5);
            String datee=rs.getString(6);
            String datem=rs.getString(7);
           
            Object[] stock={id,codef,dates,cmd,banque,datee,datem};
            dts.addRow(stock);
            }
      jTable1.setModel(dts);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "erreur dans l'affichage du stock"+ex.getMessage());
        }
    }
    //select attestation_rib.id,fournisseur.Fournisseur,attestation_rib.Saisie_Arret,attestation_rib.Commande_Marche,attestation_rib.Code_Frs,banque.Banque,ville.Agence,ville.Ville,banque.N_Compte,attestation_rib.Date_Ecrit,attestation_rib.Dte_MAJ,attestation_rib.Arrivee FROM attestation_rib,fournisseur,banque,ville WHERE attestation_rib.Code_Frs=fournisseur.Code_Frs && attestation_rib.Banque=ville.id && banque.id_Ville=ville.id && attestation_rib.Date_Ecrit && attestation_rib.Dte_MAJ && attestation_rib.Arrivee
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelxx;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldxx;
    // End of variables declaration//GEN-END:variables
}
