
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zakaria
 */
public class PAcceuil extends javax.swing.JFrame {
     Connection con;
   

    /**
     * Creates new form PAcceuil
     */
    public PAcceuil() {
        initComponents();
        setTitle("Accueil");
        this.setVisible(true);
        con=BaseDonne.getInstance().getConnexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnajouter = new javax.swing.JButton();
        btnchercher = new javax.swing.JButton();
        btnmodifier = new javax.swing.JButton();
        btnsupprimer = new javax.swing.JButton();
        btnquitter = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Afficher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 204, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("                 ATTESTATION RIB");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(147, 59, 457, 72);

        btnajouter.setBackground(new java.awt.Color(0, 204, 0));
        btnajouter.setText("Ajouter");
        btnajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajouterActionPerformed(evt);
            }
        });
        jPanel1.add(btnajouter);
        btnajouter.setBounds(52, 190, 167, 31);

        btnchercher.setBackground(new java.awt.Color(0, 204, 0));
        btnchercher.setText("Chercher");
        btnchercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchercherActionPerformed(evt);
            }
        });
        jPanel1.add(btnchercher);
        btnchercher.setBounds(52, 231, 167, 31);

        btnmodifier.setBackground(new java.awt.Color(0, 204, 0));
        btnmodifier.setText("Modifier");
        btnmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifierActionPerformed(evt);
            }
        });
        jPanel1.add(btnmodifier);
        btnmodifier.setBounds(52, 273, 167, 31);

        btnsupprimer.setBackground(new java.awt.Color(0, 204, 0));
        btnsupprimer.setText("Supprimer");
        btnsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupprimerActionPerformed(evt);
            }
        });
        jPanel1.add(btnsupprimer);
        btnsupprimer.setBounds(50, 350, 167, 31);

        btnquitter.setBackground(new java.awt.Color(0, 204, 0));
        btnquitter.setText("Quitter");
        btnquitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitterActionPerformed(evt);
            }
        });
        jPanel1.add(btnquitter);
        btnquitter.setBounds(50, 390, 167, 31);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ocp.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 61, 99);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/123.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(261, 155, 410, 275);

        Afficher.setBackground(new java.awt.Color(0, 204, 0));
        Afficher.setText("Afficher");
        Afficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherActionPerformed(evt);
            }
        });
        jPanel1.add(Afficher);
        Afficher.setBounds(53, 310, 160, 31);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnchercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchercherActionPerformed
      PreparedStatement state;
         try {
            chercher ch= new chercher();
         } catch (SQLException ex) {
             Logger.getLogger(PAcceuil.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btnchercherActionPerformed

    private void btnquitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitterActionPerformed
      System.exit(0);
    }//GEN-LAST:event_btnquitterActionPerformed

    private void btnajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouterActionPerformed
      PreparedStatement state;
      //state=con.prepareStatement();
      Ajouter aj = new Ajouter();
        
     
         try {
             state=con.prepareStatement("select Fournisseur,Code_Frs from fournisseur");
             ResultSet result=state.executeQuery();
             aj.jComboBox1.removeAllItems();
             aj.jComboBox2.removeAllItems();
             while(result.next())
             {
                 aj.jComboBox1.addItem(result.getString(1));
                 aj.jComboBox2.addItem(result.getString(2));

             }
             state=con.prepareStatement("select Banque,N_Compte from banque");
             result=state.executeQuery();
             aj.jComboBoxBanque.removeAllItems();
             aj.jComboBoxnumcompte.removeAllItems();
             while(result.next())
             {
                 aj.jComboBoxBanque.addItem(result.getString(1));
                 aj.jComboBoxnumcompte.addItem(result.getString(2));

             }
             state=con.prepareStatement("select Ville,Agence from ville");
             result=state.executeQuery();
             aj.jComboBoxAgence.removeAllItems();
             aj.jComboBoxVille.removeAllItems();
             while(result.next())
             {
                 aj.jComboBoxVille.addItem(result.getString(1));
                 aj.jComboBoxAgence.addItem(result.getString(2));

             }
             
             
             
//             state=con.prepareStatement("insert into attestation_rib values(?,?,?,?,?,?,?,?,?)");
//             state.setInt(1, 0);
//             state.setInt(2, Integer.valueOf(aj.jComboBox2.getSelectedItem().toString()));
//             state.setString(3,aj.fieldlsaisie.getText());
//             state.setString(4,aj.fieldcmd.getText());
//             state.setInt(5, Integer.valueOf(String.valueOf(aj.jComboBoxBanque.getSelectedItem().toString())));
//             state.setString(6,aj.jComboBoxAgence.getSelectedItem().toString());
//             state.setString(7,aj.jComboBoxVille.getSelectedItem().toString());
//             state.setInt(8, Integer.valueOf(aj.fieldN_Order.toString()));
//             state.setString(9,aj.fieldArrive.toString());

                    
             
             
             
             
         } catch (SQLException ex) {
             Logger.getLogger(PAcceuil.class.getName()).log(Level.SEVERE, null, ex);
         }
      
      
    }//GEN-LAST:event_btnajouterActionPerformed

    private void btnmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifierActionPerformed
        aff r= new aff();
        //state=con.prepareStatement();
        
    }//GEN-LAST:event_btnmodifierActionPerformed

    private void btnsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupprimerActionPerformed
        
        Suppression supp = new Suppression();
     
    }//GEN-LAST:event_btnsupprimerActionPerformed

    private void AfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherActionPerformed
        
        
        attestation_RIB rib= new attestation_RIB();
        
        
        
        
        
    }//GEN-LAST:event_AfficherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PAcceuil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Afficher;
    private javax.swing.JButton btnajouter;
    private javax.swing.JButton btnchercher;
    private javax.swing.JButton btnmodifier;
    private javax.swing.JButton btnquitter;
    private javax.swing.JButton btnsupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
